# Generated by Django 4.0.2 on 2023-10-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='producrs/product_cover/', verbose_name='product image'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='comment text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='point_product',
            field=models.CharField(choices=[('1', 'Very bad'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'Prefect')], max_length=10, verbose_name='what is your score?'),
        ),
    ]
